apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rso-iot-reports
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rso-iot-reports
    spec:
      containers:
      - image: rsostream/rsostreamreports:0.02
        name: rso-iot-reports
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: rso-iot
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
# kubectl set image deployment/rso-iot-dummy-consumer rso-dummy-consumer=rsostream/dummyconsumer:0.01 #setting a new image to a deployment
